### PR TITLE
update to rebar3

### PR DESCRIPTION
**Pull request by tsloughter**
Likely not something  you want to merge outright but I thought I'd open this for discussion.

It would be possible to use a `rebar.config.script` to support both rebar2 and rebar3.

### CODE REVIEW

**Comment by aeden** [comment]
Any thoughts on the CI failure?

**Comment by tsloughter** [comment]
Ah yup, one minute, didn't notice the travis file. travis is trying to use rebar2.

**Comment by rikribbers** [comment]
Just happen to see that you commited rebar.lock.  That is not needed and can be ingnored

default .gitignore generated by rebar3 itself is:

.rebar3
_*
.eunit
*.o
*.beam
*.plt
*.swp
*.swo
.erlang.cookie
ebin
log
erl_crash.dump
.rebar
_rel
_deps
_plugins
_tdeps
logs
_build

**Comment by tsloughter** [comment]
No, the rebar.lock should be committed.

**Comment by rikribbers** [comment]
Why? Don't see that yet but I'm not the expert here...

**Comment by tsloughter** [comment]
Because if you don't commit it you lose the purpose of locking :), everyone will continue to potentially get different versions when they fetch the project.

**Comment by rikribbers** [comment]
Thx. That's something I could or should have come up with myself.... still learning though...

**Comment by cmeiklejohn** [comment]
:+1:, would also like to see this merged.

**Comment by cmeiklejohn** [comment]
Is there anything we can do to get this merged in?

**Comment by aeden** [comment]
@cmeiklejohn unfortunately last time I tried I could not build because it breaks with dns_erlang: https://github.com/aetrion/dns_erlang/pull/5

**Comment by cmeiklejohn** [comment]
@aeden cool, will look at that other PR and see what we can do to help out!

**Comment by aeden** [comment]
I'd like to get rebar3 completely integrated into the build process, but right now this PR has conflicts. If you would like to have it considered please fix the conflicts with master and I will see if I can get a compile working locally.

Right now rebar3 is working to run eunit tests and and dialyzer, so I've added these to make test, however `./rebar3 compile` is failing for me.

**Comment by rikribbers** [comment]
I don't have much time to work on this, will see what I can do.

**Comment by aeden** [comment]
Closing this out as I have now merged a branch with rebar3 in it into the master.

**Pull request closed without merging**
